version: '3'
services:
  sql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: lcstracker
      MYSQL_USER: basic
      MYSQL_PASSWORD: lowpass
    ports:
      - "3306":"3306"
  wordpress:
    depends_on:
      - sql-db
    ports:
      - "8080:8080"
    restart: always